name: vpos-revisit

channels:
  - conda-forge
  - defaults

dependencies:
  # channel-specific
  - astropy
  - astro-gala
  - pytest

  # core scientific python
  - python
  - pip
  - numpy
  - scipy
  - pandas

  # plotting packages
  - matplotlib
  - seaborn

  # for my workflow
  - jupyter
  - jupyterlab
